### ISSUE TITLE
[1.16-pre5] Server crash on start

### ISSUE THREAD

**Issue by kwpugh** [lucaargolo/kibe#1]
This mod looks awesome, bring some classic mod elements to Fabric.

One snag, crashes on server start up.

Log:  https://gist.github.com/kwpugh/1c78353ac22ad793b8dcce33ee156718

**Comment by SDUBZ** [comment]
[crash-2020-06-16_23.58.58-client.txt](https://github.com/lucaargolo/kibe/files/4787006/crash-2020-06-16_23.58.58-client.txt)
i get the same crash on load

**Comment by lucaargolo** [comment]
Hey guys, sorry it took long to answer this, but GitHub never notified me. It should be fixed now.

**Comment by kwpugh** [comment]
Not sure what version of Fabric this is built with, but it crashes on 1.16-pre7

Log:  https://gist.github.com/kwpugh/de730d1ae3fb286bd4376c2cc5807d5c

**Comment by lucaargolo** [comment]
@kwpugh It is built on 1.16-pre6, but it is only working until 1.16-pre5 because one of the dependencies (PlayerAbilityLib) is not yet working on 1.16-pre6+.
