### ISSUE TITLE
Lasso can't pick up tamed mobs, or horses - 1.16.1-1.1.6-BETA

### ISSUE THREAD

**Issue by shikyo13** [lucaargolo/kibe#10]
1. When trying to pick up tamed mobs like cat or dog they sit, even when sneaking. 

2. When trying to pick up a horse tamed or untamed, they perform their right click interaction instead of being picked up by lasso.

**Comment by lucaargolo** [comment]
I rewrote the Lasso logic to avoid this, so it should be fixed in 1.1.9. Thanks for reporting!
