### ISSUE TITLE
Crash client side when loading

### ISSUE THREAD

**Issue by Nimstar01** [lucaargolo/kibe#109]
Hello using the 1.7 version on a server and when I try to load into the game I get this error message. Can't seem to find anyone that has that issue. I have all the required files.
![error log](https://user-images.githubusercontent.com/92470054/137189405-b4924503-8170-4958-9ff0-016e3028d091.PNG)

**Comment by lucaargolo** [comment]
Do you have the mod in the client and the server?

**Comment by Nimstar01** [comment]
No I just have it server side. Do I need to have it on both?

**Comment by lucaargolo** [comment]
Yes, you do.
