### ISSUE TITLE
suggestion: lava vacuum ring

### ISSUE THREAD

**Issue by Katorone** [lucaargolo/kibe#11]
Lava is a hassle to deal with.  While resistance is great, it doesn't help us miners get to the resources.
A ring that could void a lava source block would be very helpful.  The player would point the ring in the direction of a lava source block.  If this block is in the interaction range of the player, it would be removed.

**Comment by lucaargolo** [comment]
Hmmm, I like this idea. Maybe something like a Lava Sponge would be more fitting or even something like the [Lava Absorbant Sponge](https://terraria.gamepedia.com/Lava_Absorbant_Sponge) from Terraria. I'll probably add it in the next update. Thanks for the suggestion.

**Comment by lucaargolo** [comment]
Hey, so I added a Void Bucket in the latest release, it should help to remove large quantities of lava. It works as a regular bucket but you can never fill it. Maybe I'll add a Lava Sponge later that could improve this even more, but for now, that's it. 
If you really want it though, you can check out [this mod](https://www.curseforge.com/minecraft/mc-mods/pumice).

**Comment by Katorone** [comment]
This is great, thank you!
