### ISSUE TITLE
glider is not working

### ISSUE THREAD

**Issue by wilibago** [lucaargolo/kibe#111]
im trying the modpack benchmark on cursedforge and i cant use the gliders when i right click i equip it but cant glide with it

**Comment by lucaargolo** [comment]
Is this still reproducible in the latest release? I wasn't able to do it so I'm thinking it probably was some kind of cursed mod incompatibility.

**Comment by lucaargolo** [comment]
Closing this since I wasn't able to reproduce it and no one else reported it.
