### ISSUE TITLE
Block tick crash upon placing Fluid Hopper, repeatedly crashes on login

### ISSUE THREAD

**Issue by SCPRedMage** [lucaargolo/kibe#116]
Tried to place a fluid hopper pointed into a tank and the game immediately crashed. Upon attempting to reconnect, the game crashes again.
[latest.log](https://github.com/lucaargolo/kibe/files/7551754/latest.log)

**Comment by lucaargolo** [comment]
This has already been fixed. Please update to 1.9.4-BETA
