### ISSUE TITLE
[Help] Enabling Rings

### ISSUE THREAD

**Issue by iOceanus** [lucaargolo/kibe#117]
Hey folks, I'm pretty new to modding Minecraft and its intricacies, and I am stuck. I'm unsure how I'm supposed to enable rings. Clearly it says to Shift click to enable. I would think that that is pretty self-explanatory, but I have done so with both left and right click to no avail. What am I doing incorrectly? I'm also new to GitHub so I'm unsure if this is the right place for the question. Apologies ahead of time if not.

Edit: I looked in the Kibe config but found nothing relevant.

![Minecraft Screenshot 2021 11 20 - 11 25 52 14 (2)](https://user-images.githubusercontent.com/82404439/142733820-4ec1577a-5db7-449c-b4ac-953439c89328.png)

**Comment by ZestyBlaze** [comment]
Hold the ring in your hand (Out of your inventory so actually in game) and shift right click it

**Comment by iOceanus** [comment]
> Hold the ring in your hand (Out of your inventory so actually in game) and shift right click it

Your reply prompted me to investigate further since I had already done that. I switched around my keybinds when I started the game, and the description for the rings doesn't reflect that. I figured it out thanks to you. Cheers!
