### ISSUE TITLE
Fluid hoppers do not work horizontally

### ISSUE THREAD

**Issue by Adirelle** [lucaargolo/kibe#123]
I am tried to build a small "lava farm" using Kibe fluid hoppers, cauldrons and pointed dripstone:

![2021-12-25_10 34 01](https://user-images.githubusercontent.com/24633/147382266-dce9dfde-c549-4bcb-950c-98aa494fe896.png)

However, it seems that fluid hoppers do not work like regular hoppers: they do not move fluid horizontally, even though their model suggests they should. E.g. if the left hopper gets filled with lava, it does not move it to the right hopper.

Minecraft 1.18.1
Kibe 1.9.4-BETA

**Comment by lucaargolo** [comment]
This should be fixed in the latest 1.9.5 release!
