### ISSUE TITLE
Growing bamboo in chunk loader

### ISSUE THREAD

**Issue by MrLunchbox** [lucaargolo/kibe#128]
When the Chunk Loader is active any bamboo in the 5x5 chunk wont grow

**Comment by JacobDB** [comment]
Same with sugar cane, I thought I was going crazy

**Comment by wackoamd1** [comment]
https://github.com/lucaargolo/kibe/issues/120

**Comment by lucaargolo** [comment]
This should be fixed in the latest 1.9.5 release!
