### ISSUE TITLE
(Suggestion) Endermen should get moved on conveyor belts

### ISSUE THREAD

**Issue by GenericQuinn** [lucaargolo/kibe#129]
In my mob farm made with cursed earth, the endermen just stand there unaffected.

**Comment by kulcris** [comment]
Endermen are 3 tall, make sure you give them enough room to walk as if the room is 3 tall and the conveyer belt is 1/10 tall that puts the enderman inside of the ceiling  (you could line the roof with halfblocks if you want to narrow the space as much as possible)

**Comment by lucaargolo** [comment]
Just tested it and endermans are indeed being moved by conveyors belt. You were probably not giving them enough room to be pushed.
