### ISSUE TITLE
Cursed Dirt not checking valid spawn requirements (at least for enderman)

### ISSUE THREAD

**Issue by Katorone** [lucaargolo/kibe#13]
The areas around cursed dirt mobfarms get infested with enderman.  Even if these farms have a 2 high ceiling.
What we suspect is happening, is that despite the 2 block spawn height, endermen are still spawned by the Cursed Dirt.  This gives the endermen a tick of suffocation damage, and they immediately teleport.

Every few hours I use /kill to clean up these endermen, usually about 1100 get killed.

**Comment by lucaargolo** [comment]
Thanks for reporting! I'll take a look at it as soon as I can.
