### ISSUE TITLE
Issue interaction Golden Lasso and Mythic Mounts (Benchmark II)

### ISSUE THREAD

**Issue by subtumaka** [lucaargolo/kibe#130]
Some strange interactions with golden lasso, and by extension Diamond Lasso and mythic mounts mobs in the Benchmark II pack. 
Unknown if persists standalone.
Attempting to pick up a mount with right click causes some strange desync in multiplayer sessions, other players seeing player on mount while player seeing off mount and mount in lasso. 
Moving lasso around inventory while mount is inside causes mount to be kicked out of lasso, and placed back where it was first picked up, as well as being invisible. Lasso shows contents as "animals"

**Comment by lucaargolo** [comment]
Fixed in https://github.com/lucaargolo/kibe/commit/da2b1206955be007865513597dab428c86eaa63a
