### ISSUE TITLE
Vacuum Hopper GUI, Glass Bottle and shift+click

### ISSUE THREAD

**Issue by Adirelle** [lucaargolo/kibe#14]
Given I put a stack of Glass Bottles in input sloft of the Vacuum Hopper,
Then it shows a certain number of Bottle o' Enchanting in the output slot.
If I shift-click the output slot, I initially get the indicated number of Bottles o' Enchanting.
But when I close the Vacuum Hopper GUI, the number of Glass Bottles and Bottles o' Enchanting in my inventory changes.

Also, I could not guess how many mB of Liquid XP each Bottle o' Enchanting contains (same question for buckets, though).

BTW, what one could do with a bucket of Liquid XP ?

**Comment by lucaargolo** [comment]
Hello, thanks for reporting, I'll take a look asap.
The amount of XP a bottle o' Enchanting contains is randomly decided by Minecraft when you throw it at the ground, but the recipe needs 333mb because that's the value a bottle can hold (you need 3 bottles to empty a cauldron).
Currently, there's nothing you can do with a bucket of Liquid XP, other than placing it on the ground and using it for decoration, but I have plans for using it in the future.

**Comment by Adirelle** [comment]
Here are some screenshots to better explain what is happening:

1. I put 9 bottles in the vacuum hopper:
![2020-08-02_18 26 14](https://user-images.githubusercontent.com/24633/89127725-2ff44a80-d4f0-11ea-83df-407d1da14131.png)
2. I shift-click on the output slot. It gives me 8 bottles o' enchanting and leave 1 bottle in the input slot.
![2020-08-02_18 26 19](https://user-images.githubusercontent.com/24633/89127726-31257780-d4f0-11ea-955a-af86aa441549.png)
3. When I close the GUI, the number of bottles o' enchanting bumps to 20:
![2020-08-02_18 26 22](https://user-images.githubusercontent.com/24633/89127727-31257780-d4f0-11ea-8d61-9b2b943577b7.png)

**Comment by Adirelle** [comment]
While you are on it, could the input and output slots be available to hoppers, to insert bottles/empty buckets and extract full ones.

**Comment by lucaargolo** [comment]
Hey, so I updated a lot of things inside the mod and when I went to test this I could not reproduce this bug. I don't know if I unknowingly fixed it. Can you try to reproduce this in version 1.2?

**Comment by Adirelle** [comment]
I'll give it a try ASAP.

**Comment by Adirelle** [comment]
So... I was wrong. But I'm starting to identify a pattern (maybe): the duplication happens when there is more liquid xp in the vaccum than what the bottle stack can contain, e.g. 1300mb for one bottle consumes 1000mb and output 3 bottles.

**Comment by Adirelle** [comment]
Confirmed, even with kibe alone 1.2 on 1.16.2.

Steps to reproduce:
* Place a Vacuum Hopper.
* Use Bottle o' Enchanting to fill it above 1000mb.
* Place one Glass Bottle in the input slot.
* A Bottle o' Enchanting appears in the output slot: shift-click it.
* You get 3 Bottle o' Enchanting back ! The Liquid XP in the Vacuum is consumed accordingly (e.g. from 1008 to 9mb).

**Comment by Adirelle** [comment]
Another try: 2 bottles with ~6000mb gives me 18 Bottles o' Enchanting that "bumps" to 20 after I close the GUI.

**Comment by lucaargolo** [comment]
Could you try to reproduce the bug in this pre-release?
[kibe-1.16.2-1.2.1-BETA.jar.zip](https://github.com/lucaargolo/kibe/files/5076585/kibe-1.16.2-1.2.1-BETA.jar.zip)

**Comment by Adirelle** [comment]
It seems to fix it.
