### ISSUE TITLE
Chunkloaders don't load enderman farms

### ISSUE THREAD

**Issue by vaporvee** [lucaargolo/kibe#140]
When i want to use a chunloader for my enderman farm and put it where they should spawn they just don't when i'm in the same dimension. i want it to work with my me system with wireless chests at home. but when i use a player as a chunkloader it works

**Comment by lucaargolo** [comment]
This should be fixed in the latest 1.9.5 release!

**Comment by vaporvee** [comment]
No the enderman spawn now but the end dimension isn't loaded

**Comment by lucaargolo** [comment]
oh no, i'll test this asap

**Comment by vaporvee** [comment]
still problems with that if you tried fixing this in 1.9.6

**Comment by vaporvee** [comment]
maybe some performance mod unloading the dimension? but players load it so it should hopefullly be possible

**Comment by lucaargolo** [comment]
yeah most likely i think, tested it multiple times in 1.9.6 and the end/nether were being correctly loaded with chunk loaders

**Comment by vaporvee** [comment]
very weird sad that i can't find out wich one is doing this
i could send you the modpack if you have a method or something

**Comment by vaporvee** [comment]
oh wait so i get items out of this dimension with wireless chests and stuff but the enderman don't spawn when i'm not in the dimension

**Comment by vaporvee** [comment]
so i tested a bit arround and found out when you are still in the dimension but move away from the enderman farm they also stop spawning so the dimension is loaded but the endermen still don't spawn. Maybe forcing the game to think there is a player or something? idk how chunkloaders work exactly also maybe reopen this issue
