### ISSUE TITLE
Chunk loader stops growth and spreading

### ISSUE THREAD

**Issue by ftog-thorgal** [lucaargolo/kibe#142]
Modpack: Benchmark 2 version 1.0.0
Fabric: 0.13.3
Kibe: kibe-1.9.4-BETA+1.18.jar

How I tested and can replicate this issue (regardless of dimension, being on claimed or unclaimed land) is by planting fresh crop and having a few dirt blocks surrounded by grass waiting to be spread. I turn on /gamerule randomTickSpeed 500 and saplings, crop, and grass spread rapidly.

Reset to tickspeed 1, fresh saplings, crop, and dirt. Put down a chunk loader and go afk for 20 minutes. Nothing has grown or spread. Increase tickspeed to 500, nothing changes. I can go afk for 20 minutes and nothing changed.

So I don't know how this (doesn't) work, but growth/spreading tick seems to be 0 when inside chunk loaded chunks.

**Comment by lucaargolo** [comment]
This has already been fixed in 1.9.6
