### ISSUE TITLE
Chunkloader prevents crops from growing

### ISSUE THREAD

**Issue by Oxydark** [lucaargolo/kibe#143]
mod version 1.9.4

([this](https://www.curseforge.com/minecraft/modpacks/dreamcraft-new) modpack V10)

what happens:

when i setup the chunkloader to load the "modern industrialization" part of my base alle the maschines from "MI" are loaded and working normal but the crops wont grow (testet with sugarcane and wheat)

**Comment by lucaargolo** [comment]
This is already fixed on the 1.9.6 update.
