### ISSUE TITLE
Crash: AllOfFabric4, Comparator and tank crash game.

### ISSUE THREAD

**Issue by waremon9** [lucaargolo/kibe#144]
Playing modpack "All of fabric 4", using a comparator in substractor mode to check if a tank is full lead to the game crashing when the player use the XP drain to fill the tank with liquid XP.

**Comment by waremon9** [comment]
[crash-2022-03-19_15.12.35-server.txt](https://github.com/lucaargolo/kibe/files/8309506/crash-2022-03-19_15.12.35-server.txt)

Added crash report.
I'll try testing other thing since report say xp drain caused it but it worked well until now and still work outside of a comparator setup.

results:
Everything that change the tank value with a comparator looking at it will crash the game.
 - xp drain
 - xp shower
 - bucket
 - transfert from another tank using fluid hopper / fluid pipe from other mod / placing another tank next to it

**Comment by glubo** [comment]
Similar crash in "All of fabric 5 1.3.0", when kibe tank is full, monitored by comparator, and fluid pipe is trying to pull from the tank.

https://pastebin.com/raSMGqWr

**Comment by MJung84** [comment]
> Similar crash in "All of fabric 5 1.3.0", when kibe tank is full, monitored by comparator, and fluid pipe is trying to pull from the tank.
> 
> https://pastebin.com/raSMGqWr

Just just had that Issue as well. Same error log. It just happens with the normal Tank. The entangled Tank works fine.

**Comment by ouroborus** [comment]
Still exists in AOF5 1.5.1. Using kibe-1.9.9-BETA+1.18.jar

Not just a crash, also prevents the world from reloading.
