### ISSUE TITLE
Spikes have unseen faces

### ISSUE THREAD

**Issue by haykam821** [lucaargolo/kibe#147]
There are a few unnecessary bottom faces present in the `kibe:block/spikes` model. Since the spikes get thinner as they extend upwards, these bottom faces will never be seen.

![](https://user-images.githubusercontent.com/24855774/163699393-c4227c1b-cb0c-4ca4-9244-30e4f299e081.png)

**Comment by lucaargolo** [comment]
Already fixed that but forgot to close this 😅
