### ISSUE TITLE
Vacuum Hopper converts water to XP Bottles

### ISSUE THREAD

**Issue by MSandro** [lucaargolo/kibe#149]
![image](https://user-images.githubusercontent.com/10937159/164276572-7dc70045-6a4a-4d52-b8ed-cfe05b81386f.png)
Why can I create XP Bottles out of water in the Vacuum Hopper?!?
weird bug.

**Comment by MSandro** [comment]
![image](https://user-images.githubusercontent.com/10937159/164276926-8a1d17dd-fbd8-41e5-be90-0637d051cf22.png)

**Comment by MSandro** [comment]
![image](https://user-images.githubusercontent.com/10937159/168800963-4de81171-b241-4bd5-bef5-8b74c592cc17.png)
same Problem in 1.18.2, PLEASE FIX THIS!!!

**Comment by lucaargolo** [comment]
That should be fixed on 1.9.8. Thank you for your report!
