### ISSUE TITLE
[Suggestion] Enchantable diamond spikes

### ISSUE THREAD

**Issue by Adirelle** [lucaargolo/kibe#16]
Allow diamond spikes to be enchanted, either like a sword (or an axe) or by a subset or enchantments:
* Looting,
* Smite / Bane of Arthropods / Sharpness,
* maybe Efficiency (to reduce the delay between damages ?).

**Comment by lucaargolo** [comment]
Hey, that's actually a really good idea, but I've decided to not implement it. It would make the Spikes code too complex and I like them for how simple they are. Maybe I'll work on this in the future.
