### ISSUE TITLE
Lasso eats the first mob it collects

### ISSUE THREAD

**Issue by trevorjd** [lucaargolo/kibe#160]
Playing All of Fabric 5 1.2.4 with kibe-1.9.7-BETA+1.18

A freshly crafted lasso (tested with both Diamond and Golden) will not re-place the captured mob, on its first use only. Subsequent captures are released as expected. Tested with both crafted and spawned in lassos. Tested with Sheep, Cows and Villagers.

Not tested with Kibe in isolation, just as a part of the pack.

**Comment by jaz-monz** [comment]
ive a similar issue- ther seems to be a glitch (only tested on diamond lasso so far) where if you move the diamond lasso out of your hotbar and then return it, the lasso will reset and the mob that was in it is gone. it seems to happen sporadically? unsure- we've lost a fair bit of good mobs like this...
