### ISSUE TITLE
Crash with indium when rendering entangled bags in the inventory

### ISSUE THREAD

**Issue by ryleu** [lucaargolo/kibe#163]
I used `/give` to get an entangled bag and after I closed my inventory and re-opened it, my game crashed. It now crashes whenever I try to open my inventory, now that the item is there.

Here's a crashy log: https://crashy.net/DBHAYPsdZ8eIcT0cdgeC

And here's the stack trace: https://cdn.discordapp.com/attachments/810959625306243095/993904981482684567/stacktrace.txt

**Comment by ryleu** [comment]
It also seems to happen with the entangled bucket: https://crashy.net/PJolCTh5jo8sbsZMp9Zb

**Comment by lucaargolo** [comment]
Just tested with the most recent releases for Sodium and Indium in 1.19 and wasn't able to reproduce it. This is most likely being caused by something else and not Kibe's fault.
![image](https://user-images.githubusercontent.com/49497195/179907548-2dac3acc-1f84-4bb9-8bde-0b22247bd015.png)

**Comment by ryleu** [comment]
hmm, it may be dashloader. i'll take it to them and see what i can do
