### ISSUE TITLE
Tank and Drawbridge

### ISSUE THREAD

**Issue by Romz24** [lucaargolo/kibe#166]
When I place these items in my world, my game crashes (even though the server is still running).

Mod version: **Kibe 1.9.9-BETA**

[crash-2022-07-27_10.18.09-client.txt](https://github.com/lucaargolo/kibe/files/9196530/crash-2022-07-27_10.18.09-client.txt)

**Comment by lucaargolo** [comment]
This is OptiFine/OptiFabric fault.

**Comment by kyubichan** [comment]
I'd like to know how to fix that big without delete optifabric 'cause i need optifabric to resourcepacks.
