### ISSUE TITLE
Invisible blocks

### ISSUE THREAD

**Issue by Romz24** [lucaargolo/kibe#168]
Some blocks from the mod are invisible in REI, and they are also not visible if I place them in the game world. This happened when I installed Sodium, if I install OptiFine and OptiFabric instead, the client just crashes ([link to problem](https://github.com/lucaargolo/kibe/issues/166)).

List items:
- Drawbridge
- Entangled Bucket
- Entangled Bag
- Tank

![image](https://user-images.githubusercontent.com/2458113/181593936-c4911b7e-9f9d-40bf-937b-9dd67a3bebfa.png) ![image](https://user-images.githubusercontent.com/2458113/181593045-53ec8145-577c-4383-8705-e1d1b13aa2fd.png)
![image](https://user-images.githubusercontent.com/2458113/181593108-c350d3b6-970f-44b6-9c18-8a9c38c0af0b.png)

**Comment by KodaiFangs** [comment]
this happens to me too

**Comment by Romz24** [comment]
If you are using [sodium](https://www.curseforge.com/minecraft/mc-mods/sodium), you need to add [indium](https://www.curseforge.com/minecraft/mc-mods/indium) to it in order for the blocks to display correctly. I think this issue has been resolved and can be closed.
