### ISSUE TITLE
Kibe chunk loader server issues?

### ISSUE THREAD

**Issue by DirtyPro** [lucaargolo/kibe#169]
I am currently playing on a Mod pack called: Another Quality Modpack 1.18.2 version 1.3.2 Kibe version is 1.9.7-beta+1.18.
The modpack doesn't have any chunk loaders and the only way to obtain kibes chunkloader is from creative. 
when i use it i get this response: The chunk loader is offline because it's owner already reached the limit of active chunk loaders. 
so im guessing there is a ini file somewhere in the server settings that we could up the limit? 
If so would you know where that location would be?

**Comment by lucaargolo** [comment]
Hey, the modpack author probably disabled the chunk loaders... You can reenable them by editing the .minecraft/config/kibe.json file and setting maxPerPlayer in the chunkLoaderModule to -1, or any value greater than 0.
