### ISSUE TITLE
No Icon for Drawbridge, Entangled Bag & Bucket, and Tank(?)

### ISSUE THREAD

**Issue by RandomLive** [lucaargolo/kibe#172]
I'm playing on 1.19.2 if that makes any difference to anything, but yeah, I don't see the textures for these four items, plus the normal Tank if there's supposed to be one (probably not considering how it's completely invisible when placed until there's XP in it but it'd still be nice to have some indication of that inventory slot not being empty)

![Minecraft Screenshot 2022 09 14 - 19 24 42 95](https://user-images.githubusercontent.com/113549313/190234011-a80e0618-6c44-46ae-82c5-76c805329581.png)

![Minecraft Screenshot 2022 09 14 - 19 24 37 64](https://user-images.githubusercontent.com/113549313/190234042-f5634f89-7856-464c-8e02-770e53f96d06.png)

![Minecraft Screenshot 2022 09 14 - 19 24 31 33](https://user-images.githubusercontent.com/113549313/190234057-960fa689-63c2-4c67-a559-68a466f91ba2.png)

![Minecraft Screenshot 2022 09 14 - 19 24 35 15](https://user-images.githubusercontent.com/113549313/190234072-d4d46fc8-b98a-44d1-82ad-bd9933cb1d82.png)

**Comment by lucaargolo** [comment]
You're probably using sodium without indium, or another mod that breaks the fabric render api.
