### ISSUE TITLE
[Bug] Cursed Droplets won't drop

### ISSUE THREAD

**Issue by Traktool** [lucaargolo/kibe#175]
Hi !

I've tried in creative to spawn many Withers (over 400) on a Diamond Spike (with the addon to enchant it Looting III) and I've got exactly 0 Cursed Droplets, 1 stack and 4 Wither Skulls, so I guess the Cursed Droplets can't be dropped

Good luck to fix it !

Minecraft 1.18.2
Fabric 0.14.9
Kibe 1.9.9 Beta

**Comment by lucaargolo** [comment]
Hello, I wasn't able to reproduce this. I'm pretty sure there is a mod that adds wither skeletons that don't drop custom loot, so maybe that's it? Are you using a wither mob spawner by any chance? In any case, it's probably some other mod causing incompatibility.
