### ISSUE TITLE
Vacuum Hopper wastes XP orbs when full

### ISSUE THREAD

**Issue by Adirelle** [lucaargolo/kibe#19]
When the Vacuum Hopper is almost full (15880 or more), it continues to attract and consume XP orbs though it cannot transform them into liquid XP because it would overflow.

Minecraft 1.16.2.
Kibe 1.2.

**Comment by lucaargolo** [comment]
Hey there. This is an intended behavior. I did it this way cause when you have a mob farm that's running on a server 24/7, and the mobs keep dropping infinite XP, it can pretty easily kill the server within a few hours. 
I'll take a look at the "almost full" part though. It's supposed to be completely filled before it starts to trash XP.
