### ISSUE TITLE
[Suggestion] Vacuum hopper and regular hoppers

### ISSUE THREAD

**Issue by Adirelle** [lucaargolo/kibe#20]
Hey, long time no see ! :)

Could the input slot of the vacuum hopper accepts glass bottles from hoppers ? (Maybe the main inventory should not accept items).
Could the bottles in the output slot be gathered by a hopper ?

Thanks.

**Comment by Kisonu** [comment]
I think it might be easier to separate the ITEM and EXPERIECE pieces of the vacuum hopper into separate blocks. Personally I'd love to see that done. hopper input into the XP vacuum would accept glass bottle, which could then be piped out/collected, and the ITEM vacuum would just pull items in. (you could set up the XP vacuum with a dropper clock to eject the XP bottles, which could then be picked up with general mob grinder loot via the ITEM vacuum) then again, maybe I'm just over-complicating this.. lol

**Comment by Adirelle** [comment]
This is a good idea. However, using a regular hopper under either blocks should be sufficient to extract their items. This should also allow most pipe mods to work with them out of the box.

**Comment by Arcanocito** [comment]
I think this woud be a good addition, at the moment i am using a vaccum hopper with a liquid hopper underneath. This vaccuum hopper is filled with wooden shovels to not catch items, there is a second one next to it catching the items that i just let the 15k run full. Having these seperate would make it alot nicer :D
