### ISSUE TITLE
[Question] Clarification on chunkloader configuration

### ISSUE THREAD

**Issue by Icecreep109** [lucaargolo/kibe#205]
I am running a server which has this mod (among others in the pack) and would like to adjust the behavior of chunk loaders.  I tried to look both here & curseforge, but wasn't able to find documentation on the following.

What exactly does CheckForPlayers do? Does it mean the loaders only work if the owner of the loader is online?  Also, what is the unit in maxOfflineTime?  I imagine it is in hours, but want to confirm.

**Comment by lucaargolo** [comment]
> Does it mean the loaders only work if the owner of the loader is online?

Yes

> What is the unit in maxOfflineTime?

Its seconds

It would probably be best if you used Discord to ask questions like this since I only check GitHub issues when updating the mod every few months. 😅
