### ISSUE TITLE
Entangled chest and Entangled tank FPS DROP 

### ISSUE THREAD

**Issue by jojo-amin** [lucaargolo/kibe#229]
in the prominence 2 RPG modpack, whenever you observe the items in the REI gui or have them in your inventory or place them, they cause frames to drop from 300 to about 30 or so, only those two items have this problem as i checked all the other kibe items, is there a known way to fix this? I assume it is because of their textures or something? these two items were disabled in the modpack by item obliterator (among other ones)

i isolated the mod on its own and it doesnt have that issue, it only occurs in the prominence 2 modpack, would you have any idea what could be causing this?

**Comment by iSoulEs** [comment]
This fps issue keeps happening, any ideas?
