### ISSUE TITLE
[Bug] Glider right wing recipe produces a glider left wing

### ISSUE THREAD

**Issue by Adirelle** [lucaargolo/kibe#23]
Looks like a copy-pasta error.

Version 1.3.1

**Comment by lucaargolo** [comment]
Uhhh, I'm probably blind but I can't find the broken recipe. Can you send me a screenshot?

**Comment by Adirelle** [comment]
![2020-08-24_21 17 59](https://user-images.githubusercontent.com/24633/91086545-59b41380-e64f-11ea-9a7a-8d758f4e856b.png)

**Comment by lucaargolo** [comment]
Oof, I kinda forgot Minecraft have mirrored recipes. Anyway, that should be fixed in 1.3.2
