### ISSUE TITLE
hopper into big torch = crash on server

### ISSUE THREAD

**Issue by Monster-Zer0** [lucaargolo/kibe#25]
took a big torch.

loaded a few stacks of torches into it.

wanted to see if I could feed them in via a hopper.

place hopper on top

open hopper, place stack of torches.

crash on linux server

https://hastebin.com/aqujiqatub.coffeescript

**Comment by lucaargolo** [comment]
This appears to be an incompatibility issue with the item module from Lib Block Attributes. I'm only embedding the fluid and core modules so another mod must be the culprit.
Also, I tested with the item module in server and client environments and I could not reproduce this.
I strongly recommend opening an issue report on the [Lib Block Attributes GitHub page](https://github.com/AlexIIL/LibBlockAttributes/issues). 
If this ends up being an incompatibility on Kibe's end, I'll happily fix it.
