### ISSUE TITLE
Entangled Chest & Tank Don't Render

### ISSUE THREAD

**Issue by Afrocntrik** [lucaargolo/kibe#29]
![2020-09-09_03 00 03](https://user-images.githubusercontent.com/11052983/92565586-e1517300-f248-11ea-967c-047eb80d0e22.png)
![2020-09-09_03 00 11](https://user-images.githubusercontent.com/11052983/92565603-e6162700-f248-11ea-8600-1d92eb837933.png)
Using Canvas v1.0.933

**Comment by lucaargolo** [comment]
Hello, this should be fixed in version 1.4.2. Thanks for reporting!
BTW the custom fluid hopper model mentioned in #30 was working correctly.
