### ISSUE TITLE
Unable to Override Item Model

### ISSUE THREAD

**Issue by Afrocntrik** [lucaargolo/kibe#30]
![2020-09-09_03 00 16](https://user-images.githubusercontent.com/11052983/92565720-1d84d380-f249-11ea-8fdd-62801e6eaf49.png)
Here's what I'm going for
![2020-09-09_03 00 24](https://user-images.githubusercontent.com/11052983/92565727-207fc400-f249-11ea-8eea-a98d19cac4e2.png)
Here's my model to do just that
![image](https://user-images.githubusercontent.com/11052983/92565825-4dcc7200-f249-11ea-947c-0a5ef97d6026.png)

**Comment by lucaargolo** [comment]
Hello, I just tested with another resource pack and overriding the item model worked as expected.
Can you send me your resource pack? And your client's log?

**Comment by Afrocntrik** [comment]
Yeah sure, been trying at this for a while probably my fault but I can't figure out what I'm doing wrong
[resources.zip](https://github.com/lucaargolo/kibe/files/5196616/resources.zip)

**Comment by lucaargolo** [comment]
![image](https://user-images.githubusercontent.com/49497195/92626894-f823b400-f2a0-11ea-9323-79fb50181145.png)
Well, it worked

**Comment by Afrocntrik** [comment]
Odd I'm not sure why it doesn't work for me

**Comment by Afrocntrik** [comment]
Thank you for helping me figure this out

**Comment by lucaargolo** [comment]
Probably because you're playing with canvas, I'll test compatibility with it right now. Will update you on the other issue.
