### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by rekkep** [lucaargolo/kibe#33]
REI shows that you could get cursed droplets by killing evry mob, but i get it only by killing wither skeleton

**Comment by Katorone** [comment]
That's a side effect of RER.  All mobs do drop the droplets, but only when spawned by cursed earth.  Otherwise, as you say, it only gets dropped by wither skeles.

**Comment by lucaargolo** [comment]
As Katorone said, all the mobs with the Cursed Effect will drop Cursed Droplets, but RER does not show it correctly. It should be reported to them.
