### ISSUE TITLE
XP Showers don't take from liquid in tank blocks aside from the one it's attached to

### ISSUE THREAD

**Issue by TheGag96** [lucaargolo/kibe#35]
Kibe version: 1.4.3
Minecraft version: 1.16.2
Modpack: All of Fabric 3 v2.0.5 (with removed mods from v2.0.4 readded)

I had 3 tanks placed on top of each other, with liquid XP entirely filling the lowest tank block, and a little bit more in the middle one. I placed the XP Shower on the side of the top tank block. Doing so did not have it pull out any XP - it can only pull out of the tank block it's currently attached to.

(Unrelated: thanks for this mod!! It's great seeing all of these cool features from OpenBlocks and elsewhere implemented in a modern Fabric mod. The rework of the old Ender Storage mod is especially cool. Hope to see more from you!)

**Comment by lucaargolo** [comment]
Hi, glad you liked the mod!
This is actually intended behaviour, Kibe's tanks are gravity based, so you can only extract fluid when the tank actually has fluid... If you want a non-gravity based tank you can use Industrial Revolution ones, but they only stack vertically.
