### ISSUE TITLE
Vacuum Hopper does not work with @ezpas Puller Pipes

### ISSUE THREAD

**Issue by oliverjanik** [lucaargolo/kibe#36]
I'm already using the bottom side with fluid hopper. So I'm trying to pull items out of the side using @ezpas puller pipes.

**Comment by lucaargolo** [comment]
Hi, thanks for reporting!
IIRC, this is a problem on EZPaS end as my mod is completely compatible with vanilla inventories (aka hoppers, droppers, etc). You should talk to EZPaS's dev. If this somehow ends up being a bug on my end, I'll happily fix it.

**Comment by lucaargolo** [comment]
Nvm, that was actually my fault. This should be fixed in 1.4.4. Thanks for reporting!
