### ISSUE TITLE
Chunkloader does not appear to work on multiplayer server

### ISSUE THREAD

**Issue by ElKameleon** [lucaargolo/kibe#40]
Minecraft 1.16.4
Kibe 1.5-beta

Chunkloader doesn't seem to actually load any chunks on a multiplayer server. I had a portal set up to put mobs through and kill them on the other side, then send back the drops, but they would just disappear and nothing happened. I had to have another player go stand by the killing machine on the other side, and everything worked as intended. Not sure what i'm doing wrong?

**Comment by lucaargolo** [comment]
Hey, so, the chunk loader is not a player replacement... Vanilla only spawn mobs when a player is near, and when there's no one nearby the mobs naturally despawn. That's probably what is happening in your case.
As a solution for this problem you can use the Cursed Dirt from this mod (you can get it by planting a Cursed Seed in dirt or grass in the dark and then letting it spread) that spawns mobs even when there's no one around and keeps the mobs from despawning.
If you think this isn't your problem, the best way to test if a Chunk Loader is working is to set up a furnace with a lot of items, leave the chunk and check after some time to see if the items got smelted.

**Comment by ElKameleon** [comment]
You are correct, I tried it with a furnace and it did work. There's still the mystery of why this is working in singleplayer, but in multiplayer a character is needed to keep the mobs from despawning the minute they go through the portal.
