### ISSUE TITLE
Big Torch crashes game whenever putting torches in rapidly

### ISSUE THREAD

**Issue by DeathSupportsLife** [lucaargolo/kibe#41]
Or maybe it's Mouse Wheelie causing it I don't know I'm not a scientist

Crash Report:

[crash-2020-11-27_11.36.53-client.txt](https://github.com/lucaargolo/kibe/files/5610499/crash-2020-11-27_11.36.53-client.txt)

**Comment by lucaargolo** [comment]
Yeah, this sounds like a problem on my end... Unfortunately, I'm in the last weeks of my college semester and there's a lot of exams and assignments I have to study for. I'll probably only be able to solve this in 2-3 weeks.

**Comment by GregariousJB** [comment]
Kibe 1.6.7-BETA is still crashing when doing this.

[crash-2021-05-09_15.56.10-client.txt](https://github.com/lucaargolo/kibe/files/6448306/crash-2021-05-09_15.56.10-client.txt)

To duplicate:
1. Cheat-add a bunch of stacks of small torches
2. Shift+click+drag them all into the Big Torch quickly
3. Crash
