### ISSUE TITLE
Big torch does not block enderman spawning in the end

### ISSUE THREAD

**Issue by T-Dark0** [lucaargolo/kibe#45]
It appears that endermen are able to spawn in the radius of big torches in the end. Weirdly enough, most enderman spawns are blocked, but not quite all of them: waiting around for 20-ish seconds on the main end island after covering it in the radius of big torches will result in one or two endermen spawning.

This was witnessed in All Of Fabric 3, so it might be caused by Better End, which appears to mess with enderman spawning in [this mixin](https://github.com/paulevsGitch/BetterEnd/blob/master/src/main/java/ru/betterend/mixin/common/HostileEntityMixin.java). I'm reporting the bug here because I would imagine that the big torch should prevent enderman spawning regardless of other factors, or at least either prevent either all or none of them.

**Comment by lucaargolo** [comment]
Oh yeah, it's most likely that mixin lol, it's in the same place Kibe does its mixin. I'll take a look at it later.

**Comment by lucaargolo** [comment]
Can't reproduce in the latest release of Better End... Guess they fixed it!
