### ISSUE TITLE
[SUGGESTION] Vacuum Hopper should output its Item Level via Comparator!

### ISSUE THREAD

**Issue by MSandro** [lucaargolo/kibe#52]
![image](https://user-images.githubusercontent.com/10937159/107585573-cc657b00-6bfe-11eb-9190-55c8b62b91c4.png)
I've tried to put an Redstone Comparator to an Vacuum Hopper but it doesn't output its level...

**Comment by lucaargolo** [comment]
Sorry for taking so long to answer, but this should be an easy one... As soon as I get back home I will implement this.
