### ISSUE TITLE
Big torch does not affect guardian spawners

### ISSUE THREAD

**Issue by srnyx** [lucaargolo/kibe#53]
The big torch affects every spawner (well, maybe not all, I didn't test all of them) except for the guardian spawner

**Comment by srnyx** [comment]
It also doesn't affect Blaze Spawners

**Comment by lucaargolo** [comment]
Yes, currently the big torch only affects mobs that need to be in the dark to spawn. Guardians and Blazes have a different condition and I don't know how I'll implement them.

**Comment by srnyx** [comment]
> Yes, currently the big torch only affects mobs that need to be in the dark to spawn. Guardians and Blazes have a different condition and I don't know how I'll implement them.

Ah, ok. Makes sense to be honest.
