### ISSUE TITLE
Angel ring through dimensions

### ISSUE THREAD

**Issue by srnyx** [lucaargolo/kibe#54]
The Angel Ring doesn't work when switching through dimensions via teleporting (and maybe normally too, not too sure). This causes problems with mods like Immersive Portals, /tpa, and /home.

**Comment by lucaargolo** [comment]
I tested this with the latest release of Immersive Portals and it worked fine but i did indeed get a bug when teleporting directly between dimensions. I think this is a bug in the attributes api i'm using but i'm not entirely sure. 
Disabling and re-enabling the ring solved the issue.
I'll see if i can fix this later.
