### ISSUE TITLE
Bubble Column / Entangled Bucket

### ISSUE THREAD

**Issue by srnyx** [lucaargolo/kibe#55]
Client crashes when trying to use an entangled bucket on a bubble column: https://pastebin.com/mmu61PAE

**Comment by lucaargolo** [comment]
What do you mean by a bubble column?

**Comment by srnyx** [comment]
> What do you mean by a bubble column?

A column of water sources with soul sand at the bottom (https://minecraft.gamepedia.com/Bubble_Column).

**Comment by lucaargolo** [comment]
Huh, I see, I'll try to fix it right now.

**Comment by lucaargolo** [comment]
Sorry for taking too long to answer but that should be fixed in the 1.6.4-BETA release.

**Comment by srnyx** [comment]
> Sorry for taking too long to answer but that should be fixed in the 1.6.4-BETA release.

Alright, thank you!
