### ISSUE TITLE
Fluid Hopper doesnt seem to work

### ISSUE THREAD

**Issue by IdealIdeas** [lucaargolo/kibe#56]
Ive tried the fluid hopper on various machines and it doesnt seem take from tanks and output into anything.

**Comment by lucaargolo** [comment]
![image](https://user-images.githubusercontent.com/49497195/110205464-c60d9c00-7e56-11eb-8557-b8c320e020c4.png)
Fluid hoppers are indeed working in the latest release. You're probably doing something wrong, using incompatible or wrongly configured machines.
