### ISSUE TITLE
Cursed Dirt doesnt work in nether

### ISSUE THREAD

**Issue by IdealIdeas** [lucaargolo/kibe#57]
Cursed dirt doesnt appear to work in the nether. I think it should.

**Comment by lucaargolo** [comment]
![image](https://user-images.githubusercontent.com/49497195/110205520-213f8e80-7e57-11eb-8220-08cb29f40ef3.png)
Cursed dirt is indeed working in the nether in the latest release.

**Comment by IdealIdeas** [comment]
![Doesnt Work](https://user-images.githubusercontent.com/3318728/110206925-4f68a280-7e46-11eb-962a-1ce1f8ccdafd.png)

Cursed dirt doesnt work in nether for me.

**Comment by lucaargolo** [comment]
As we can see in the chat, no mobs are allowed to spawn in this biome.
