### ISSUE TITLE
water glitch

### ISSUE THREAD

**Issue by ShadowSlayerFX1** [lucaargolo/kibe#59]
hold ice in your hand and watch to water or ice and glass and than you have a annoying glitch

end cyan glass

**Comment by ShadowSlayerFX1** [comment]
and cyan glass

**Comment by K0-RR** [comment]
?? I don't understand anything and you should add a screenshot
![image](https://user-images.githubusercontent.com/43277609/111066403-1cb25000-84bf-11eb-8e37-0723238ee832.png)

**Comment by ShadowSlayerFX1** [comment]
![2021-03-14_12 28 55](https://user-images.githubusercontent.com/80198511/111066774-0c02d980-84c1-11eb-96d1-870794ce3b22.png)
![2021-03-14_12 28 53](https://user-images.githubusercontent.com/80198511/111066776-10c78d80-84c1-11eb-9dbe-9c5865a05377.png)
![2021-03-14_12 28 24](https://user-images.githubusercontent.com/80198511/111066778-1329e780-84c1-11eb-968f-f613f3005aec.png)
![2021-03-14_12 28 28](https://user-images.githubusercontent.com/80198511/111066779-14f3ab00-84c1-11eb-8949-2fad26c8b94c.png)
![2021-03-14_12 28 30](https://user-images.githubusercontent.com/80198511/111066781-16bd6e80-84c1-11eb-9c84-aaa6edbcc351.png)
![2021-03-14_12 28 38](https://user-images.githubusercontent.com/80198511/111066784-191fc880-84c1-11eb-827b-4e504032b43a.png)

**Comment by K0-RR** [comment]
Are you sure it's caused by Kibe? How to reproduce this? I can hold and place glass and ice without this bug.

**Comment by ShadowSlayerFX1** [comment]
i tested it and with this mod i have this bug and without this mod not

**Comment by ShadowSlayerFX1** [comment]
????

**Comment by ShadowSlayerFX1** [comment]
you mean you play now vanilla and have this bug???

**Comment by K0-RR** [comment]
I said I cannot reproduce it at all.

**Comment by decosawa** [comment]
Hey ShadowSlayerFX1,

Are you using Sodium?

If you're using it, know that it requires Indium to work with mods.

[indium-1.0.2.zip](https://github.com/lucaargolo/kibe/files/6136832/indium-1.0.2.zip)

This is a zip that contains indium, extracts the zip and puts the jar in your mods folder.

**Comment by K0-RR** [comment]
@andytxr AFAIK Kibe doesn’t depend of FRAPI so why you are recommending Indium? Also it would just crash for @ShadowSlayerFX1 because he probably use stable Sodium release.

**Comment by decosawa** [comment]
Kibe depends yes on FRAPI and it's just a suggestion to see if it works.

**Comment by lucaargolo** [comment]
![image](https://user-images.githubusercontent.com/49497195/111079532-2779de80-84d9-11eb-86a3-e5740785a028.png)
I was not able to reproduce this bug. Seeing as you have other mods installed and I don't even mess with water and translucent rendering, I'll rule this out as a mod incompatibility issue. Try updating/removing all your other mods to see which one is the actual culprit. If you're using Sodium, you can try installing Indium as other users suggested. If even after removing/updating all other mods this issue persists, you may reopen this issue report.
