### ISSUE TITLE
suggestion: silk touch cursed dirt

### ISSUE THREAD

**Issue by milkev** [lucaargolo/kibe#6]
it would be usefull to be able to silk touch cursed dirt, and place it manually.

**Comment by lucaargolo** [comment]
Not being able to recover placed cursed dirt is actually an intended behavior. It's supposed to be a hard-to-get resource and farming it with silk touch picks would just make it very easy.

**Comment by milkev** [comment]
hmmm i see, this is just the way mods with cursed dirt have worked in the past.
it does make sense one wouldnt want to be carrying around dirt that buffs spawn rates into oblivion though
