### ISSUE TITLE
Can't find the wooden bucket in the creative inventory.

### ISSUE THREAD

**Issue by K0-RR** [lucaargolo/kibe#60]
![image](https://user-images.githubusercontent.com/43277609/111066368-f2f92900-84be-11eb-8b12-a503ef4924fa.png)

**Comment by supsm** [comment]
I don't think any kibe items are available in the creative inventory, you'll probably just have to /give them to yourself

**Comment by lucaargolo** [comment]
I'm fixing this right now, next release will make all Kibe items searchable.

**Comment by lucaargolo** [comment]
Version 1.6.6-BETA should have this issue fixed!
