### ISSUE TITLE
[Suggestions] Various Block/Item suggestions

### ISSUE THREAD

**Issue by IdealIdeas** [lucaargolo/kibe#62]
Just some suggestions for future Blocks/Items id like to see in this mod since this mod is a collection of random utility blocks.

- [Nether Rod/Shrine of the Blaze](https://lumien.net/rtwiki/blocks/rain-shield/):  When placed down, it prevents Rain/Snow in the chunk its placed as well as the adjacent chunks. Block will emit fire particles from itself when it is currently Raining/Snowing

- Heat Lamp: When supplied with redstone power, it will melt away Snow/Ice, up to 16 blocks away

- Clock: Keeps track of world time, can be configured what times it can emit a redstone signal. Kinda like an advanced Daylight Sensor with more configurability

- Gold Spikes: Killed mobs only drop experience

- Wood Spikes: Kills mobs and doesnt drop anything

- Advanced Enchanting Table: Kinda like the [EnderIO Enchanter](https://ftbwiki.org/Enchanter_(EnderIO)), Allows player to take book and quill and create any enchanted book of any level for a predetermined amount of Experience. Can also be fed Liquid XP.

- Noise Inhibitor: When placed, you can open a Gui to select which active sounds to mute. Specified noises can either be inhibited by 50% or completely muted. Also has button to toggle area of effect visibility. There are a couple Muffler mods for fabric, but nothing as configurable as this.

- Breaker: Breaks blocks that are directly in front of it. Has a slot to input a "Gear" into it.

- Gear: Used in Breaker, has a couple different Tiers. More or less just a way to gate what blocks can be broken with Breaker. Tiers are the same as the Pickaxes. IE: Iron gears cant be used to break Obsidian, but Diamond Gears can.

- Placer: Has a small inventory, Randomly picks from inventory and places block down directly in front of itself if there are no blocks in its way.

- Gong: Players can strike it with Melee or Ranged weapons and can be activated with redstone. When activated, will alert/attract all hostile mobs within a 64 block radius of it.

- Barrels: Similar to the tank, costs more to make but can hold far more liquids. 3 different Tiers. Basic, Standard, Advanced.
Basic holds 24 Buckets, Standard holds 64 Buckets, Advanced holds 512 Buckets.

- Dye Mixer: Takes Red/Blue/Green Dye and can mix varying amounts of those 3 to create any of the other dye colors.

- Igniter: Can be orientated in any direction, when given a redstone signal it will ignite the space in front of it. Its like a Dispenser with a Flint and Steel but can be used forever. If a block is directly in front of it, it can ignite the space past that block.

- Escape Rope: Charges up like bow and arrow, once charged it will teleport the player to the surface directly above where the player is. Has durability, uses more durability the deeper underground you are. The surface is defined by any block that has an unblocked view to the sky.

- Steve Statue: Can be placed in the world, the world treats it like its an actual player. So things like mob spawners will work when the statue is within their work area.

**Comment by lucaargolo** [comment]
First of all, thank you very much for all the ideas, most of which I implemented in Kibe 1.7. Some were not implemented cause I thought they didn't exactly fit with the mod or were too complex for me. One of those is the Steve Statue, although chunk loaders already sort of work for most things, and you can place a Cursed Dirt block under a Mob Spawner to keep it running without a player nearby. The majority of these were implemented thought. Thanks again and hope you like it.
