### ISSUE TITLE
Excessive Packets send by Kybe about Tubes

### ISSUE THREAD

**Issue by frqnny** [lucaargolo/kibe#64]
I created a mod that println's all packets received and sent by the server, and so far the log is filled with Kibe packages about some type of dirty tank packet. 

How to reproduce:
Launch Kibe and attached mod together
See log to see how bad it erally is 
[mod-is-inside-here.zip](https://github.com/lucaargolo/kibe/files/6174752/mod-is-inside-here.zip)

Issues with lots of players may arise because sending that crazy amount of packets will end up in worse latencies on servers and will cause lag on clients. It is urgent you fix this.

**Comment by lucaargolo** [comment]
Hi, are the packets being sent or received by the clients? There are a few packets that Kibe has to send every tick to keep the Entangled Tanks synchronized in the inventory and in the world. Yes sending a packet every tick sounds dangerous and wrong but it's a very small packet, smaller than the ones vanilla sends every tick. It shouldn't cause any issues unless you're hosting a server with 1000 people or more. Ofc there's always a possibility that I implemented something wrong and the packets are indeed causing issues, but no one in the AOF servers reported anything to me yet, and this system has been in place for a long time. Are you having any real issues or you're just seeing the packets being spammed and thinking there's something wrong?

**Comment by frqnny** [comment]
![image](https://user-images.githubusercontent.com/45723631/111888775-f7897a00-89b5-11eb-96ff-2d323d8eadb7.png)
As per the image, it appears to be this one. Client 2 server.
Yes, we see the packets being spammed.
Also, AOF has been having some issues with performance and we believe it might likely be your mod. 
Having 10-30 people on the AOF server, sending the same packet, will end up creating bad lag for the server if it receives about 20 on average. 

The reason AOF is just reporting it now was that AOF implemented several ways to mitigate a memory leak, such as restarting every two hours. 

![image](https://user-images.githubusercontent.com/45723631/111888835-84343800-89b6-11eb-810f-5a9984ff4fb6.png)
As you can see in this image, networking is a big problem.
When you see Kibe spamming the packets severely as per the log, you begin to think that indeed it is this mod causing problems.

**Comment by lucaargolo** [comment]
As explained in the AOF discord server, the mod now only sends packets if the list of tanks requested by the client changed. This should greatly reduce the quantity of sent packets.
