### ISSUE TITLE
bug: entangled chest and import bus from ae2

### ISSUE THREAD

**Issue by mlunax** [lucaargolo/kibe#65]
When import bus from ae2 is connected to the entagled chest this chest is not connected to any chest in this same code.

**Comment by lucaargolo** [comment]
![image](https://user-images.githubusercontent.com/49497195/112042677-8cab8080-8b26-11eb-8aa3-8131dad9f923.png)
Just tested it and it's working fine.

**Comment by mlunax** [comment]
tested again after restart the server - 
my bad
i don't know why it wasn't work before
sorry
