### ISSUE TITLE
Ghasts get trapped by conveyors when spawned on cursed earth

### ISSUE THREAD

**Issue by SuddenTurmoil** [lucaargolo/kibe#70]
When a ghast gets spawned by cursed earth under a conveyor the ghast gets trapped seemingly between the two. It results in ghasts stuck in floors until they despawn. This appears to happen regardless of the ceiling height.

**Comment by SuddenTurmoil** [comment]
Using V1.6.3 BETA on All of Fabric 3. I will try updating the mod on my client and server and see if that resolves the issue as I just noticed it is out of date by quite a bit.

**Comment by SuddenTurmoil** [comment]
This is still an issue on V1.6.7 BETA.

**Comment by lucaargolo** [comment]
Yes, the mod hasn't updated since you opened both issues and I haven't got the time to test everything yet, but I'll do it asap.

**Comment by SuddenTurmoil** [comment]
Sorry, I didn't mean to nag you. I had just noticed that the pack I am running is using an older version of the mod so I wanted to update the mod to the newest version and retest to make sure you hadn't fixed it in a new version that I hadn't tried yet and therefore waste your time. I really appreciate you looking into it.

**Comment by lucaargolo** [comment]
https://user-images.githubusercontent.com/49497195/119065909-fe803900-b9b4-11eb-84ff-38b800edec2d.mp4

I just built this cursed dirt farm in the nether using the latest 1.6.8-BETA release and everything works fine. As you can see the ghasts do get trapped at first but after a few seconds, they free themselves. Just make sure there's enough space for them to move.
