### ISSUE TITLE
Big Torch not working with Starlight/Phosphor 

### ISSUE THREAD

**Issue by srnyx** [lucaargolo/kibe#77]
The Big Torches on my server just randomly stopped working, no clue why.
Anyone having a similar issue or know why this is happening to me?

**Comment by lucaargolo** [comment]
What version are you using? Have you tried breaking the torch and placing it again?

**Comment by srnyx** [comment]
> What version are you using?

v1.7-BETA

> Have you tried breaking the torch and placing it again?

I'll try that today, once I get home.

**Comment by srnyx** [comment]
> > Have you tried breaking the torch and placing it again?
> 
> I'll try that today, once I get home.

Still doesn't work

**Comment by ryleu** [comment]
It also doesn’t work on bewitchment ghosts or werewolves, though i think this is an unrelated issue

**Comment by srnyx** [comment]
> It also doesn’t work on bewitchment ghosts or werewolves, though i think this is an unrelated issue

Mine doesn't work on any mob...

**Comment by lucaargolo** [comment]
Just tested the Big Torch on the latest release and it seems to be working fine. Are you sure you're setting it up correctly? You have to place torches inside it. Also, the issue with bewitchment ghosts and werewolves should also be fixed in the latest release.

**Comment by srnyx** [comment]
> Just tested the Big Torch on the latest release and it seems to be working fine. Are you sure you're setting it up correctly? You have to place torches inside it. Also, the issue with bewitchment ghosts and werewolves should also be fixed in the latest release.

Yes, it was working fine before but then just randomly stopped, without anyone touching it (I had it hidden underground).

Was anything regarding big torches and mob spawners changed?

**Comment by srnyx** [comment]
Still not working

**Comment by SenKetZu** [comment]
we have a similar issue on our server, i was because of starlight- phosphor changin the spawn behavior

**Comment by ryleu** [comment]
> we have a similar issue on our server, i was because of starlight- phosphor changin the spawn behavior

That could totally be it. I’m currently using phosphor. Should I try Starlight?

**Comment by SenKetZu** [comment]
we have to disble both, none of them works with kibe right now

**Comment by ryleu** [comment]
> we have to disble both, none of them works with kibe right now

@srnyx could you test uninstalling starlight / phosphor? If it turns out to be starlight / phosphor, you should rename it to “lighting performance mods break big torch”

Before you do that, make sure both kibe and starlight / phosphor are the latest version.

**Comment by srnyx** [comment]
> @srnyx could you test uninstalling starlight / phosphor? If it turns out to be starlight / phosphor, you should rename it to “lighting performance mods break big torch”
> 
> 
> 
> Before you do that, make sure both live and starlight / phosphor are the latest version.

I've recently shutdown my modded server.
This also means I'm leaving a majority of the Fabric/modded community.

*It probably is Starlight/Phosphor*

**Comment by Zank82** [comment]
Could this be why ghasts are still spawning for me

**Comment by TheSnowyChickens** [comment]
Hello,
on our server we have the problem with starlight and kibe "1.9.8-BETA".

We play AoF 5 v1.3.1 and we must change to Starlight, because Phosphor created some sub chunk sky light issues.
*and now some players talk about a not working big torch now*

**Comment by lucaargolo** [comment]
Update to 1.9.9
