### ISSUE TITLE
Multiple lasso bugs version 1.16.1 1.1.5-Beta

### ISSUE THREAD

**Issue by shikyo13** [lucaargolo/kibe#8]
1 . Gold and Diamond lasso cannot pick up villagers, you just open the GUI instead ( I managed to do it ONCE by accident and could not ever again ) 

2. If you pick up a zombie with a Diamond lasso, there is a chance you will put down a baby zombie instead. After picking this up and putting it down multiple times, it then spawned with a full set of gold enchanted armor it did not previously have. 

3. Placing a mob down against a wall results in it ending up inside the wall and suffocating, often in the blocks above where you placed it. Even placing down on the floor near a wall they often take damage.

**Comment by lucaargolo** [comment]
Hey, thanks for the report. It should be fixed in 1.1.6

**Comment by shikyo13** [comment]
Awesome, can confirm that all appears to be working as expected now. Thanks!
