### ISSUE TITLE
1.17 Creative menu crash 

### ISSUE THREAD

**Issue by sleepy-evelyn** [lucaargolo/kibe#81]
**Description:** Kibe crashes when clicking on it's creative menu tab
**Version**: kibe-1.7.2-BETA+1.17
**Environment:** AOF4s 1.17 experimental pack, includes mods like REI, Conjuring etc... They have a link in there discord

**Crash report:** https://gist.github.com/profjb58/cda8edd5f5772e6d5c2e2642605c2d2b

p.s. just from a basic observation I see Gunpowder included in the crash log, the 2 may not be related though

```at io.github.gunpowder.api.components.ComponentsKt.getComponents(ComponentsKt.java:30)	at io.github.gunpowder.entities.ComponentHandler.initComponents(ComponentHandler.java:10)```

**Comment by Martmists-GH** [comment]
This is a gunpowder related issue, it uses Kotlin Reflect which uses the Metadata annotation on classes if available, which doesn't get remapped. See relevant Tiny Remapper issue here: https://github.com/FabricMC/tiny-remapper/issues/59

I'll publish a fix in gunpowder later today, but definitely a bug on my end.
