### ISSUE TITLE
[Suggestion] Crucible

### ISSUE THREAD

**Issue by greensad** [lucaargolo/kibe#82]
With your phenomenal rendition of cobble gens it would be awesome to have working crucibles that could interface with other mods fluid pipe/conduits (Industrial Revolution, Simple Pipes, Modern Industrialization, Tech Reborn). I have no idea what the scope of Kibe is but I love what you're doing lol, keep at it!

**Comment by lucaargolo** [comment]
Wdym by crucibles?

**Comment by greensad** [comment]
They're similar to a cauldron but their purpose is to be filled with cobble, then the cobble is melted using a block placed underneath the crucible to create lava, the lava can then be piped out of crucibles and stored in tanks or used in machines. The relevance to Kibe is that they typically pair well with cobble gens.

https://ex-nihilo-minecraft.fandom.com/wiki/Crucible

**Comment by lucaargolo** [comment]
Oh, I see. Unfortunately, I don't think this mechanic really fits this mod, especially now that Mojang added its own way of farming lava. Thanks for the suggestion tho!
