### ISSUE TITLE
Endermen aren't pushed by express conveyor belts

### ISSUE THREAD

**Issue by Flatts3000** [lucaargolo/kibe#83]
Version: 1.7.2-BETA+1.17
Modpack: All of Fabric 4

With a mob spawner that is three blocks tall, with a cursed earth floor, and the floor covered with express conveyor belts, endermen are not pushed by the conveyor belts.

**Comment by itsdinkd** [comment]
also happens on 1.17.1

**Comment by lucaargolo** [comment]
If you're talking about this:
![image](https://user-images.githubusercontent.com/49497195/129428993-6e4a5de8-85aa-432d-9c64-22026e1336f1.png)
Then it's actually intended, as the conveyor block has its own collision box. Just build it a block taller.
