### ISSUE TITLE
[Fabric] Block#rotate fails during placement with mods like Campanion

### ISSUE THREAD

**Issue by Xechorizo** [lucaargolo/kibe#91]
Horizontal orientation of Xp Shower, Placer, Breaker, etc. maintain their original orientation after specific placements.

**Describe the bug**

Placing Xp Shower, Placer, Breaker, etc. using mods like [Campanion](https://github.com/TerraformersMC/Campanion) results in the original horizontal orientation kept, instead of the new horizontal orientation. Campanion mod authors advised Block#rotate may be the cause of the failure to reorient the horizontal axis.

**To Reproduce**

Place an affected horizontally-oriented block in range or within a Campanion 1.3.5 Tent.
Pick up the Tent with the Tent Bag.
Rotate the Tent.
Place the Tent.
Observe the affected horizontally-oriented blocks have wrongly maintained their original orientation.

**Expected behavior**

Place an affected horizontally-oriented block in range or within a Campanion 1.3.5 Tent.
Pick up the Tent with the Tent Bag.
Rotate the Tent.
Place the Tent.
All blocks placed reflect the new orientation.

**Additional context**

![image](https://user-images.githubusercontent.com/14857131/128955452-936aba4b-9b81-4ec4-b37a-0b3f13a83a3e.png)

**Environment**

Minecraft v1.16.5
All The Fabric 3 v2.8.5
Kibe 1.7-BETA
Fabric v0.11.3
Fabric API v0.34.7+1.16
Oracle JDK v16.0.1

https://pastebin.com/h5ey6vz1

**Comment by lucaargolo** [comment]
Looks like I forgot to implement the Block#rotate and Block#mirror methods in my custom blocks. (Actually, I didn't even know those existed). I'll try to get it working in a future release.
