### ISSUE TITLE
Kibe causes Better End blocks to not display in REI interface

### ISSUE THREAD

**Issue by jangro** [lucaargolo/kibe#92]
I'm testing this out with the new Valhelsia Fabric modpack looking for potential additions to the pack, but it causes a bunch of the Better End textures to disappear from the REI interface, so they're all blank spots.

There are over 150 mods in there, so I don't know if this is even Kibe's fault. Though as the last mod in, it's what caused the issue. Removing it fixed it. 

I hope this is useful. I love what you've included in here and it adds a lot of the things that are in the Valhelsia 3 pack on Forge.

**Comment by lucaargolo** [comment]
Huh, this is weird, I managed to reproduce this bug in a modpack without Kibe, but when I remove all mods except for BetterEnd and REI it works fine. I'll try investigating some more.

**Comment by lucaargolo** [comment]
Okay, after further testing, I have managed to reproduce this bug using other mods (Industrial Revolution). I've talked to the Industrial Revolution dev and as I suspected this is a bug on their end. It was already reported here https://github.com/paulevsGitch/BCLib/issues/31 and the dev is looking for a fix.
