### ISSUE TITLE
Missing textures

### ISSUE THREAD

**Issue by Zank82** [lucaargolo/kibe#94]
Are texture is missing or is it just me?
First it was the tank. Now it is the entangled bucket and entangled bag and all of the colored gliders.
These items are invisible.

**Comment by lucaargolo** [comment]
Are you using Sodium? If so you have to install Indium.

**Comment by Zank82** [comment]
Installed Indium. The gliders are still not showing up but the tank and entangled stuff are, so Indium worked for that . To be clear I can see the two glider piece's in REI and the glider on my back but not any of the whole gliders on REI & as items in inventory.

**Comment by Zank82** [comment]
Apparently it's my shaders making the gliders invisible.
