### ISSUE TITLE
Cursed dirt config

### ISSUE THREAD

**Issue by clements56** [lucaargolo/kibe#97]
When I enter the IDs for mobs into the blacklist, minecraft:zombie, for example, it still spawns them. And with how your code is written this seems to be the proper way to  enter mobs into the blacklist, Is this a bug or is this my error? Thanks!

**Comment by lucaargolo** [comment]
Please send logs and a copy of your config file.

**Comment by lucaargolo** [comment]
Closing this since not enough information was provided.
