### ISSUE TITLE
[Bug] Crash when using kibe's diamond spike

### ISSUE THREAD

**Issue by kadir1243** [lucaargolo/kibe#99]
Kibe version: kibe-1.8.1-BETA+1.17
Log:
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 9/15/21, 5:08 PM
Description: Colliding entity with block

java.lang.ClassCastException: io.github.lucaargolo.kibe.utils.FakePlayerEntity incompatible with net.minecraft.class_3222
	at draylar.identity.cca.UnlockedIdentitiesComponent.unlock(UnlockedIdentitiesComponent.java:30)
	at draylar.identity.cca.UnlockedIdentitiesComponent.unlock(UnlockedIdentitiesComponent.java:43)
	at draylar.identity.api.IdentityGranting.grantByAttack(IdentityGranting.java:18)
	at net.minecraft.class_1309.handler$clk002$onDeath(class_1309.java:16785)
	at net.minecraft.class_1309.method_6078(class_1309.java)
	at net.minecraft.class_3763.method_6078(class_3763.java:178)
	at net.minecraft.class_1309.method_5643(class_1309.java:1177)
	at net.minecraft.class_3763.method_5643(class_3763.java:295)
	at io.github.lucaargolo.kibe.blocks.miscellaneous.Spikes.method_9548(Spikes.java:47)
	at net.minecraft.class_4970$class_4971.method_26178(class_4970.java:926)
	at net.minecraft.class_1297.method_5852(class_1297.java:1035)
	at net.minecraft.class_1297.method_36974(class_1297.java:739)
	at net.minecraft.class_1297.method_5784(class_1297.java:712)
	at net.minecraft.class_1309.method_26318(class_1309.java:2244)
	at net.minecraft.class_1309.method_6091(class_1309.java:2189)
	at net.minecraft.class_1309.method_6007(class_1309.java:2640)
	at net.minecraft.class_1308.method_6007(class_1308.java:539)
	at net.minecraft.class_1588.method_6007(class_1588.java:43)
	at net.minecraft.class_3763.method_6007(class_3763.java:114)
	at net.minecraft.class_1309.method_5773(class_1309.java:2346)
	at net.minecraft.class_1308.method_5773(class_1308.java:339)
	at net.minecraft.class_3218.method_18762(class_3218.java:655)
	at net.minecraft.class_3218$$Lambda$11368/0x00000000c25456a8.accept(Unknown Source)
	at net.minecraft.class_1937.method_18472(class_1937.java:483)
	at net.minecraft.class_3218.method_31420(class_3218.java:417)
	at net.minecraft.class_3218$$Lambda$11350/0x00000000c25158f0.accept(Unknown Source)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:392)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:891)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831)
	at net.minecraft.class_1132.method_3748(class_1132.java:96)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at net.minecraft.server.MinecraftServer$$Lambda$10648/0x00000000c21f9638.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:853)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at draylar.identity.cca.UnlockedIdentitiesComponent.unlock(UnlockedIdentitiesComponent.java:30)
	at draylar.identity.cca.UnlockedIdentitiesComponent.unlock(UnlockedIdentitiesComponent.java:43)
	at draylar.identity.api.IdentityGranting.grantByAttack(IdentityGranting.java:18)
	at net.minecraft.class_1309.handler$clk002$onDeath(class_1309.java:16785)
	at net.minecraft.class_1309.method_6078(class_1309.java)
	at net.minecraft.class_3763.method_6078(class_3763.java:178)
	at net.minecraft.class_1309.method_5643(class_1309.java:1177)

-- Patchouli Book Info --
Details:
	Patchouli open book context: n/a
Stacktrace:
	at net.minecraft.class_128.handler$cbk000$fillPatchouliContext(class_128.java:521)
	at net.minecraft.class_128.<init>(class_128.java:37)
	at net.minecraft.class_128.method_560(class_128.java:267)
	at net.minecraft.class_1297.method_5852(class_1297.java:1038)
	at net.minecraft.class_1297.method_36974(class_1297.java:739)
	at net.minecraft.class_1297.method_5784(class_1297.java:712)
	at net.minecraft.class_1309.method_26318(class_1309.java:2244)
	at net.minecraft.class_1309.method_6091(class_1309.java:2189)
	at net.minecraft.class_1309.method_6007(class_1309.java:2640)
	at net.minecraft.class_1308.method_6007(class_1308.java:539)
	at net.minecraft.class_1588.method_6007(class_1588.java:43)
	at net.minecraft.class_3763.method_6007(class_3763.java:114)
	at net.minecraft.class_1309.method_5773(class_1309.java:2346)
	at net.minecraft.class_1308.method_5773(class_1308.java:339)
	at net.minecraft.class_3218.method_18762(class_3218.java:655)
	at net.minecraft.class_3218$$Lambda$11368/0x00000000c25456a8.accept(Unknown Source)
	at net.minecraft.class_1937.method_18472(class_1937.java:483)
	at net.minecraft.class_3218.method_31420(class_3218.java:417)
	at net.minecraft.class_3218$$Lambda$11350/0x00000000c25158f0.accept(Unknown Source)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:392)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:891)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831)
	at net.minecraft.class_1132.method_3748(class_1132.java:96)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at net.minecraft.server.MinecraftServer$$Lambda$10648/0x00000000c21f9638.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:853)

-- Block being collided with --
Details:
	Block: Block{kibe:diamond_spikes}[facing=up]
	Block location: World: (-168,70,-846), Section: (at 8,6,2 in -11,4,-53; chunk contains blocks -176,0,-848 to -161,255,-833), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)

-- Entity being checked for collision --
Details:
	Entity Type: minecraft:pillager (net.minecraft.class_1604)
	Entity ID: 4314
	Entity Name: Yağmacı
	Entity's Exact location: -167.55, 70.50, -845.70
	Entity's Block location: World: (-168,70,-846), Section: (at 8,6,2 in -11,4,-53; chunk contains blocks -176,0,-848 to -161,255,-833), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
	Entity's Momentum: -0.08, 0.40, -0.39
	Entity's Passengers: []
	Entity's Vehicle: null

-- Entity being ticked --
Details:
	Entity Type: minecraft:pillager (net.minecraft.class_1604)
	Entity ID: 4314
	Entity Name: Yağmacı
	Entity's Exact location: -167.55, 70.50, -845.70
	Entity's Block location: World: (-168,70,-846), Section: (at 8,6,2 in -11,4,-53; chunk contains blocks -176,0,-848 to -161,255,-833), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
	Entity's Momentum: -0.08, 0.40, -0.39
	Entity's Passengers: []
	Entity's Vehicle: null

-- Affected level --
Details:
	All players: 1 total; [class_3222['Kadir1243516'/179, l='ServerLevel[New World]', x=-166.70, y=75.00, z=-844.30]]
	Chunk stats: 2986
	Level dimension: minecraft:overworld
	Level spawn location: World: (-80,69,176), Section: (at 0,5,0 in -5,4,11; chunk contains blocks -80,0,176 to -65,255,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1077457 game time, 420961 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Level weather: Rain time: 34441 (now: false), thunder time: 2814 (now: true)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16, AdoptOpenJDK
	Java VM Version: Eclipse OpenJ9 VM (JRE 16 Windows 10 amd64-64-Bit Compressed References 20210311_69 (JIT enabled, AOT enabled)
OpenJ9   - 022d65424
OMR      - 09514431e
JCL      - 0c11227a21a based on jdk-16+36), Eclipse OpenJ9
	Memory: 800745352 bytes (763 MiB) / 3344171008 bytes (3189 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 6
	Processor Vendor: AuthenticAMD
	Processor Name: AMD FX(tm)-6100 Six-Core Processor             
	Identifier: AuthenticAMD Family 21 Model 1 Stepping 2
	Microarchitecture: Bulldozer
	Frequency (GHz): 3.32
	Number of physical packages: 1
	Number of physical CPUs: 3
	Number of logical CPUs: 6
	Graphics card #0 name: NVIDIA GeForce GT 730
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x0f02
	Graphics card #0 versionInfo: DriverVersion=23.21.13.8813
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: Other
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: Other
	Virtual memory max (MB): 12387.35
	Virtual memory used (MB): 9349.63
	Swap memory total (MB): 4213.24
	Swap memory used (MB): 283.71
	JVM Flags: 6 total; -Xoptionsfile=C:\Program Files\AdoptOpenJDK\jdk-16.0.0.36-openj9\lib\options.default -Xlockword:mode=default,noLockword=java/lang/String,noLockword=java/util/MapEntry,noLockword=java/util/HashMap$Entry,noLockword=org/apache/harmony/luni/util/ModifiedMap$Entry,noLockword=java/util/Hashtable$Entry,noLockword=java/lang/invoke/MethodType,noLockword=java/lang/invoke/MethodHandle,noLockword=java/lang/invoke/CollectHandle,noLockword=java/lang/invoke/ConstructorHandle,noLockword=java/lang/invoke/ConvertHandle,noLockword=java/lang/invoke/ArgumentConversionHandle,noLockword=java/lang/invoke/AsTypeHandle,noLockword=java/lang/invoke/ExplicitCastHandle,noLockword=java/lang/invoke/FilterReturnHandle,noLockword=java/lang/invoke/DirectHandle,noLockword=java/lang/invoke/ReceiverBoundHandle,noLockword=java/lang/invoke/DynamicInvokerHandle,noLockword=java/lang/invoke/FieldHandle,noLockword=java/lang/invoke/FieldGetterHandle,noLockword=java/lang/invoke/FieldSetterHandle,noLockword=java/lang/invoke/StaticFieldGetterHandle,noLockword=java/lang/invoke/StaticFieldSetterHandle,noLockword=java/lang/invoke/IndirectHandle,noLockword=java/lang/invoke/InterfaceHandle,noLockword=java/lang/invoke/VirtualHandle,noLockword=java/lang/invoke/PrimitiveHandle,noLockword=java/lang/invoke/InvokeExactHandle,noLockword=java/lang/invoke/InvokeGenericHandle,noLockword=java/lang/invoke/VarargsCollectorHandle,noLockword=java/lang/invoke/ThunkTuple -Xjcl:jclse29 -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx4096m
	Fabric Mods: 
		additionaladditions: Additional Additions 2.1.2
		adorn: Adorn 2.1.4+1.17.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.3.10
		arcanus: Arcanus 1.11
		architectury: Architectury 2.5.27
		artifice: Artifice 0.15.3+21w07a
		autoconfig1u: Auto Config v1 Updated 3.3.1
		axolotlitemfix: Axolotl Item Fix 1.1.2
		bclib: BCLib 0.3.1
		betterend: Better End 0.11.0-pre
		betternether: Better Nether 5.1.3
		betterstrongholds: YUNG's Better Strongholds 1.17-1.1.1
		bitsandchisels: BitsAndChisels 2.5.3
		blue_endless_jankson: jankson 1.2.1
		boatcontainer: BoatContainer 1.0.0
		caelus: Caelus API 0.0.16-1.17
		cardinal-components: Cardinal Components API 3.1.1
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-block: Cardinal Components API (blocks) 3.1.1
		cardinal-components-chunk: Cardinal Components API (chunks) 3.1.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		cardinal-components-item: Cardinal Components API (items) 3.1.1
		cardinal-components-level: Cardinal Components API (world saves) 3.1.1
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 3.1.1
		cardinal-components-util: Cardinal Components API (utilities) 3.1.1
		cardinal-components-world: Cardinal Components API (worlds) 3.1.1
		charm: Charm 3.3.2
		charmonium: Charmonium 3.3.0
		chestcavity: Chest Cavity 2.13.0
		cloth-api: Cloth API 2.0.54
		cloth-armor-api-v1: Cloth Armor API v1 1.5.47
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config2: Cloth Config v5 5.0.38
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		connectiblechains: Connectible Chains 1.2.2
		crowdin-translate: CrowdinTranslate 1.3+1.17
		ctm: ConnectedTexturesMod for Fabric 0.5.1+1.17
		customlan: Custom LAN 1.17-v2.0.0
		customportalapi: Custom Portals 0.0.1-beta33-1.17
		detailab: Detail Armor Bar 2.4.3+1.17.1-fabric
		diggusmaximus: Diggus Maximus 1.4.5-1.17
		dml-refabricated: Deep Mob Learning: Refabricated 0.4.4-beta
		dml-refabricated-base: DML: Refabricated - Base 0.4.4-beta
		dml-refabricated-events: DML: Refabricated - Vanilla Events 0.4.4-beta
		dml-refabricated-modular-armor: DML: Refabricated - Glitch Armor 0.4.4-beta
		dml-refabricated-rei: DML: Refabricated - REI Integration 0.4.4-beta
		draggable-resource-packs: Draggable Resource Packs 1.0.1
		elytratrinket: Elytra Trinket 2.0.1-1.17
		enchantmentdescriptions: Enchantment Descriptions 4.0.1
		enhancedcelestials: Enhanced Celestials 2.0.4
		expandedstorage: Expanded Storage 7.1.0
		extragenerators: Extra Generators 1.0.6-BETA+1.17
		fabric: Fabric API 0.40.1+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+cbda931818
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.0+cbda931818
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+cbda931818
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.0+cbda931818
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.3+87cc6e4c18
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.10+fc40aa9d18
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-furnaces: Fabric Furnaces 2.0.1-1.17
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+cbda931818
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+cbda931818
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+cbda931818
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-language-kotlin: Fabric Language Kotlin 1.6.4+kotlin.1.5.30
		fabric-language-scala: Fabric Language Scala 1.1.0+scala.2.13.6
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446318
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+cbda931818
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa13
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+cbda931818
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+cbda931818
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+cbda931818
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.3+4658223018
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.14+4658223018
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.4+4658223018
		fabric-rendering-v1: Fabric Rendering (v1) 1.8.2+ffb6d41e18
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+198a96213d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+cbda931818
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.1+b06cb95b18
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.3.1+4658223018
		fabricloader: Fabric Loader 0.11.6
		fabrictailor: Fabric Tailor 1.6.3
		fake-player-api: Fake Player API 0.2.0
		fancymenu: FancyMenu 2.2.2
		fasttransferlib: Fast Transfer Lib 0.5.6
		fiber: fiber 0.23.0-2
		forgottenrecipes: Forgotten Recipes 1.0.2
		fpsreducer: FPS Reducer 1.23.1-mc1.17.1
		geckolib3: Geckolib 3.0.13
		hardcorequesting: Hardcore Questing Mode 1.17.1-5.6.2
		here-be-no-dragons: Here be no Dragons! 1.0.0
		identity: Identity 1.14.2-beta-1.17
		illuminations: Illuminations 1.7.2
		indium: Indium 1.0.0-dev.d797129+mc1.17.1
		indrev: Industrial Revolution 1.10.0-alpha.12
		inmis: Inmis 2.3.1-1.17
		inventorysorter: Inventory Sorter 1.8.0-1.17
		jankson: Jankson 3.0.1+j1.2.0
		java: Eclipse OpenJ9 VM 16
		kibe: Kibe 1.8.1-BETA+1.17
		konkrete: Konkrete 1.2.3
		ktdatataglib: KtDataTagLib 1.5.4
		kubejs: KubeJS 1605.3.10-build.9999
		kyrptconfig: Kytpt Config 1.1.10-1.17
		lambdabettergrass: LambdaBetterGrass 1.2.1+1.17
		lambdynlights: LambDynamicLights 2.0.2+1.17
		lazy-language-loader: lazy-language-loader 0.2.1
		lchunkloader: Literally Chunk Loader 2.0.3
		libblockattributes: LibBlockAttributes 0.9.0
		libblockattributes_core: LibBlockAttributes (Core) 0.9.0
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.9.0
		libblockattributes_items: LibBlockAttributes (Items) 0.9.0
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.1.6+1.17.1
		libninepatch: LibNinePatch 1.1.0
		linkedstorage: Linked Storage 1.3.13-1.17
		lithium: Lithium 0.7.4
		logical_zoom: Logical Zoom 0.0.11
		magna: Magna 1.5.5-1.17-pre4
		megane: megane 5.2.1
		megane-base: megane-base 5.2.1
		megane-extra-generators: megane-extra-generators 5.2.1+1.0.6-BETA-1.17
		megane-fabric-transfer: megane-fabric-transfer 5.2.1+1.1.0-3fe74aa118
		megane-fast-transfer-lib: megane-fast-transfer-lib 5.2.1+0.5.6
		megane-industrial-revolution: megane-industrial-revolution 5.2.1+1.10.0-alpha.12
		megane-kibe: megane-kibe 5.2.1+1.8.1-BETA-1.17
		megane-lib-block-attributes: megane-lib-block-attributes 5.2.1+0.9.0
		megane-modern-industrialization: megane-modern-industrialization 5.2.1+0.5.9
		megane-runtime: megane-runtime 5.2.1
		megane-team-reborn-energy: megane-team-reborn-energy 5.2.1+0.1.1
		megane-tech-reborn: megane-tech-reborn 5.2.1+5.0.6-beta-build.95
		megane-vanilla: megane-vanilla 5.2.1+1.17.1
		megane-wireless-networks: megane-wireless-networks 5.2.1+1.1.2
		minecraft: Minecraft 1.17.1
		mo_glass: Mo Glass 1.5-MC1.17.1
		mocolors: Mo' Colors 1.2.2
		modern_industrialization: Modern Industrialization 0.5.12
		modify-drops-api: Modify Drops API 0.3.2
		modmenu: Mod Menu 2.0.5
		monsters_in_the_closet: Monsters in the Closet 1.0.2+1.17
		moretotems: More Totems 2.8.0
		morevillagers-fabric: MoreVillagersFabric 2.0.4-SNAPSHOT
		mostructures: Mo' Structures 1.2.1-1.17
		omega-config: OmegaConfig 1.0.8
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_annotations: annotations 19.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.30
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.2
		org_objenesis_objenesis: objenesis 3.2
		outvoted: Outvoted 2.0.0-alpha.13
		patchouli: Patchouli 1.17-54-FABRIC
		plantinajar: Plant In A Jar 2.2.2
		playerabilitylib: Pal 1.3.0
		quarryplus: QuarryPlus 17.0.349
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		realisticfirespread: Realistic Fire Spread 1.17-3
		reborncore: Reborn Core 5.0.6-beta+build.94
		rhino: Rhino 1605.1.2-build.47
		roughlyenoughitems: Roughly Enough Items 6.0.275-alpha
		rpgdifficulty: Rpg Difficulty 1.0.7
		seasons: Fabric Seasons 1.2.2-BETA+1.17
		secretrooms: Secret Rooms 1.0.0+1.17
		seedy-behavior: Seedy Behavior 1.0.1
		servertick: Server Tick 1.5
		shulkerutils: shulkerutils 1.0.4-1.17
		sihywtcamc: sihywtcamc 1.4.1+1.17.1
		sodium: Sodium 0.3.0+build.5
		sodium-extra: Sodium Extra 0.3.4
		spark: spark 1.6.1
		spirit: Spirit 1.1.0
		spruceui: SpruceUI 3.3.0+1.17
		stacc: Stacc 1.2.3
		staffofbuilding: Staff of Building 1.3.2-1.17
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stoneholm: Stoneholm 1.3
		stonevaults: Stonevaults 1.1.0
		team_reborn_energy: Energy 2.0.0-beta1
		techreborn: Tech Reborn 5.0.6-beta+build.94
		the_aether: The Aether 1.17.1-1.5.0
		timeinabottle: Time in a Bottle 1.6-mc1.17-fabric
		toms_storage: Tom's Simple Storage Mod 1.1.15
		trinketofundying: Trinket of Undying 2.0.0-1.17
		trinkets: Trinkets 3.0.2
		trinketshulkerboxes: Trinket Shulker Boxes 2.0.0-1.17
		upgradedshulkers: Upgraded Shulkers 1.0.2-1.17
		verticalrepeaters: Vertical Repeaters 1.1.2
		villagernames: Villager Names 2.0.0
		villagershats: Goosik's Villager Hats 1.2.0
		voicechat: Simple Voice Chat 1.17.1-1.1.4
		waystones: Waystones 2.0.4
		wirelessnetworks: Wireless Networks 1.1.2
		wthit: wthit 3.8.1
		xaerominimap: Xaero's Minimap 21.15.1
		xaeroworldmap: Xaero's World Map 1.16.1
		xlpackets: XLPackets 2.0-1.17
		xp_storage: XP Storage 1.4.2+1.17.1
		xp_storage_trinkets: XP Storage - Trinkets 0.1+1.17.1
		yungsapi: YUNG's API 1.17-Fabric-16
	Player Count: 1 / 8; [class_3222['Kadir1243516'/179, l='ServerLevel[New World]', x=-166.70, y=75.00, z=-844.30]]
	Data Packs: vanilla, Fabric Mods, secretrooms:server_pack
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'

**Comment by lucaargolo** [comment]
This is being caused by Identity. Will need a fix on their side.

**Comment by kadir1243** [comment]
thanks for reply
